# ::::SETTINGS:::::::::::( Creative Button-Card Templates )::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>
_cbc_settings:
  variables:
    # :: Enable Checking for Updates ::> true|false (Default: true)
    __cbc_check_updates: true
    # :: Check Frequency (in days) ::> 7-90 (Default: 28)
    # :: This is reset if you clear your browser local storage for your Home Assistant domain.
    __cbc_check_frequency: 28
    # :: Send anonymous usage data with the update check. ::> true|false (Default: true)
    # :: Sends if you used the UI or yaml and 2 numbers, times CBCT was loaded and number of templates it was loaded for.
    # :: NO Personally identifing Information is used or stored.
    __cbc_check_send_data: true
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::/
