# ::::SETTINGS:::::::::::( Creative Button-Card Templates )::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>
_cbc_settings:
  variables:
    __cbc_check:
      # :: Enable Checking for Updates ::> true|false (Default: true) This will also disable sending data.
      updates: true

      # Check Frequncy
      # Check is performed once on first run, once 7 days after and then according to the check frequency.
      # This is reset if you clear your browser's local storage or use a new browser/device.
      # :: Check Frequency (in days) ::> 7-90 (Default: 14)
      frequency: 14

      # :: Update Available Notification ::> true|false (default: true)
      notify: true

      # Anonymous Usage Data
      # Data sent: The lovelace mode (yaml|storage) and the number times each template is used per dashboard.
      # To see exactly, type `cbcJS.stats` into your web browser console on any lovelace dashboard running CBC.
      # NO Personally identifing information is ever sent!
      # This is optional, of course, but it will really help me to plan and improve the cards, thanks.
      # :: Send anonymous usage data with the update check. ::> true|false (Default: true)
      send_data: true
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::/
