bc_config:
  variables:
    __config: >
      [[[
        const symbols = Object.getOwnPropertySymbols(this);
        const sym = symbols.filter(s => this[s].type && this[s].type == 'custom:button-card')?.[0];
        return this[sym];
      ]]]

### /END
